<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Interfaces\IBannerService.cs\**" />
    <Compile Remove="Interfaces\IBlogService.cs\**" />
    <Compile Remove="Interfaces\ICarritoService.cs\**" />
    <Compile Remove="Interfaces\ICategoriaService.cs\**" />
    <Compile Remove="Interfaces\IClienteService.cs\**" />
    <Compile Remove="Interfaces\IContactoService.cs\**" />
    <Compile Remove="Interfaces\IDetalleCarritoService.cs\**" />
    <Compile Remove="Interfaces\IDetallePedidoService.cs\**" />
    <Compile Remove="Interfaces\IEnvioService.cs\**" />
    <Compile Remove="Interfaces\IFavoritoService.cs\**" />
    <Compile Remove="Interfaces\IImagenProductoService.cs\**" />
    <Compile Remove="Interfaces\IMarcaService.cs\**" />
    <Compile Remove="Interfaces\IMetodoPagoService.cs\**" />
    <Compile Remove="Interfaces\IPedidoService.cs\**" />
    <Compile Remove="Interfaces\IPreguntaFrecuenteService.cs\**" />
    <Compile Remove="Interfaces\IProductoService.cs\**" />
    <Compile Remove="Interfaces\IResenaService.cs\**" />
    <Compile Remove="Interfaces\IRolService.cs\**" />
    <Compile Remove="Interfaces\IUsuarioService.cs\**" />
    <EmbeddedResource Remove="Interfaces\IBannerService.cs\**" />
    <EmbeddedResource Remove="Interfaces\IBlogService.cs\**" />
    <EmbeddedResource Remove="Interfaces\ICarritoService.cs\**" />
    <EmbeddedResource Remove="Interfaces\ICategoriaService.cs\**" />
    <EmbeddedResource Remove="Interfaces\IClienteService.cs\**" />
    <EmbeddedResource Remove="Interfaces\IContactoService.cs\**" />
    <EmbeddedResource Remove="Interfaces\IDetalleCarritoService.cs\**" />
    <EmbeddedResource Remove="Interfaces\IDetallePedidoService.cs\**" />
    <EmbeddedResource Remove="Interfaces\IEnvioService.cs\**" />
    <EmbeddedResource Remove="Interfaces\IFavoritoService.cs\**" />
    <EmbeddedResource Remove="Interfaces\IImagenProductoService.cs\**" />
    <EmbeddedResource Remove="Interfaces\IMarcaService.cs\**" />
    <EmbeddedResource Remove="Interfaces\IMetodoPagoService.cs\**" />
    <EmbeddedResource Remove="Interfaces\IPedidoService.cs\**" />
    <EmbeddedResource Remove="Interfaces\IPreguntaFrecuenteService.cs\**" />
    <EmbeddedResource Remove="Interfaces\IProductoService.cs\**" />
    <EmbeddedResource Remove="Interfaces\IResenaService.cs\**" />
    <EmbeddedResource Remove="Interfaces\IRolService.cs\**" />
    <EmbeddedResource Remove="Interfaces\IUsuarioService.cs\**" />
    <None Remove="Interfaces\IBannerService.cs\**" />
    <None Remove="Interfaces\IBlogService.cs\**" />
    <None Remove="Interfaces\ICarritoService.cs\**" />
    <None Remove="Interfaces\ICategoriaService.cs\**" />
    <None Remove="Interfaces\IClienteService.cs\**" />
    <None Remove="Interfaces\IContactoService.cs\**" />
    <None Remove="Interfaces\IDetalleCarritoService.cs\**" />
    <None Remove="Interfaces\IDetallePedidoService.cs\**" />
    <None Remove="Interfaces\IEnvioService.cs\**" />
    <None Remove="Interfaces\IFavoritoService.cs\**" />
    <None Remove="Interfaces\IImagenProductoService.cs\**" />
    <None Remove="Interfaces\IMarcaService.cs\**" />
    <None Remove="Interfaces\IMetodoPagoService.cs\**" />
    <None Remove="Interfaces\IPedidoService.cs\**" />
    <None Remove="Interfaces\IPreguntaFrecuenteService.cs\**" />
    <None Remove="Interfaces\IProductoService.cs\**" />
    <None Remove="Interfaces\IResenaService.cs\**" />
    <None Remove="Interfaces\IRolService.cs\**" />
    <None Remove="Interfaces\IUsuarioService.cs\**" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="Services\BannerService.cs~RF16904f5.TMP" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="16.2.0" />
    <PackageReference Include="FluentValidation" Version="12.1.1" />
    <PackageReference Include="Google.Apis.Auth" Version="1.76.0" />
    <PackageReference Include="Microsoft.AspNetCore.Identity" Version="2.3.11" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SysNova.Common\SysNova.Common.csproj" />
    <ProjectReference Include="..\SysNova.DAL\SysNova.DAL.csproj" />
    <ProjectReference Include="..\SysNova.DTO\SysNova.DTO.csproj" />
    <ProjectReference Include="..\SysNova.EN\SysNova.EN.csproj" />
    <ProjectReference Include="..\SysNova.Repository\SysNova.Repository.csproj" />
  </ItemGroup>

</Project>
